export enum Action {
  START_DRAW_TIME,
  START_ENERGY_TIME,
  START_PUT_TIME,
  START_SOMETHING_TIME,
  START_BATTLE_TIME,
  START_END_TIME,
  PUT,
  CHANGE_BATTLE_POSITION,
  USE_SOUL_CANON,
  SUMMON_MONSTER,
  ATTACK,
  USE_SOUL_BARRIER,
}
